from pydantic import BaseModel, Field

class DiseaseSearchDataResult(BaseModel):
    treatment: str = Field(description="crop diseases pathology treatment and their disease profiles.")
    medicine: str = Field(description="medicine prescription for crop diseases treatment")
    pathsogens: str = Field(description="Pathogens (fungi, bacteria, viruses) and their characteristics")

class PromptDataResult(BaseModel):
    prompt: list[str] = Field(description="Visual prompt for an AI image generation model to generate two images.")
    caption: list[str] = Field(description="short caption for wich image generated by model.")

class ImageUrlResult(BaseModel):
    imageUrl1: str = Field(description="A image url for image one generated by model.")
    imageUrl2: str = Field(description="A image url for image two generated by model.")